@create problem_name:
	bash ./new {{problem_name}}

@test problem_num:
    cargo clippy --all-targets --all-features -- -D warnings
    RUST_BACKTRACE=1 cargo test --lib test_{{problem_num}}_solution -- --nocapture

@push problem_num:
	git add ./ 
	git commit -S -m "{{problem_num}} ac"
	git push

